import React from "react";
import { FaAws, FaDocker, FaGitAlt, FaJava, FaReact, FaHtml5 } from "react-icons/fa";
import {
  SiApachekafka,
  SiCss3,
  SiElasticsearch,
  SiGooglecloud,
  SiIntellijidea,
  SiJavascript,
  SiJenkins,
  SiJunit5,
  SiKibana,
  SiKubernetes,
  SiNextdotjs,
  SiOracle,
  SiPostgresql,
  SiRabbitmq,
  SiRedis,
  SiSpring,
  SiSpringboot,
  SiTypescript
} from "react-icons/si";
import { TbApi } from "react-icons/tb";

export const skillIcons: { [key: string]: { icon: React.ReactNode; color: string } } = {
  "Java": { icon: <FaJava />, color: "#007396" },
  "Spring Boot": { icon: <SiSpringboot />, color: "#6DB33F" },
  "Spring Framework": { icon: <SiSpring />, color: "#6DB33F" },
  "JPA": { icon: <FaJava />, color: "#007396" },
  "PostgreSQL": { icon: <SiPostgresql />, color: "#336791" },
  "OracleSQL": { icon: <SiOracle />, color: "#F80000" },
  "Redis": { icon: <SiRedis />, color: "#DC382D" },
  "Docker": { icon: <FaDocker />, color: "#2496ED" },
  "Kubernetes": { icon: <SiKubernetes />, color: "#326CE5" },
  "RabbitMQ": { icon: <SiRabbitmq />, color: "#FF6600" },
  "Kafka": { icon: <SiApachekafka />, color: "#ccc9b1" },
  "Elasticsearch": { icon: <SiElasticsearch />, color: "#005571" },
  "REST API": { icon: <TbApi />, color: "#4CAF50" },
  "JUnit": { icon: <SiJunit5 />, color: "#25A162" },
  "Mockito": { icon: <TbApi />, color: "#FF6B35" },
  "Git": { icon: <FaGitAlt />, color: "#F05032" },
  "HTML5": { icon: <FaHtml5 />, color: "#E34F26" },
  "CSS3": { icon: <SiCss3 />, color: "#1572B6" },
  "JavaScript": { icon: <SiJavascript />, color: "#F7DF1E" },
  "TypeScript": { icon: <SiTypescript />, color: "#3178C6" },
  "React": { icon: <FaReact />, color: "#61DAFB" },
  "Next.js": { icon: <SiNextdotjs />, color: "#e0d2d2" },
  "React Native": { icon: <FaReact />, color: "#61DAFB" },
  "AWS": { icon: <FaAws />, color: "#FF9900" },
  "AWS S3": { icon: <FaAws />, color: "#FF9900" },
  "GCP": { icon: <SiGooglecloud />, color: "#4285F4" },
  "Kibana": { icon: <SiKibana />, color: "#005571" },
  "Jenkins": { icon: <SiJenkins />, color: "#D33833" },
  "IntelliJ IDEA": { icon: <SiIntellijidea />, color: "#000000" },
};
